import { marked, type Tokens } from "marked";
import { getProjectGraph } from "./graphService.js";
import { NODE_LABELS } from "@vibeshift/shared";

const LANE_ORDER = [
  "overview",
  "need",
  "feature",
  "spec",
] as const;

// Custom renderer: convert mermaid code blocks to <pre class="mermaid">
const renderer = new marked.Renderer();
const origCode = renderer.code.bind(renderer);
renderer.code = function (token: Tokens.Code) {
  if (token.lang === "mermaid") {
    return `<pre class="mermaid">${token.text}</pre>`;
  }
  return origCode(token);
};

marked.setOptions({ renderer, gfm: true, breaks: false });

interface TreeNode {
  id: string;
  type: string;
  title: string;
  content: string;
  children: TreeNode[];
}

function buildTree(
  nodes: { id: string; type: string; title: string; content: string }[],
  edges: { from_node_id: string; to_node_id: string; link_type: string }[]
): TreeNode[] {
  const nodeMap = new Map<string, TreeNode>();
  for (const n of nodes) {
    nodeMap.set(n.id, { ...n, children: [] });
  }

  const childIds = new Set<string>();
  for (const e of edges) {
    if (e.link_type !== "derives") continue;
    const parent = nodeMap.get(e.from_node_id);
    const child = nodeMap.get(e.to_node_id);
    if (parent && child) {
      parent.children.push(child);
      childIds.add(child.id);
    }
  }

  // Roots are nodes without incoming derives edges
  return Array.from(nodeMap.values()).filter((n) => !childIds.has(n.id));
}

function collectByLane(roots: TreeNode[]): Map<string, TreeNode[]> {
  const laneMap = new Map<string, TreeNode[]>();
  for (const lane of LANE_ORDER) {
    laneMap.set(lane, []);
  }

  function walk(node: TreeNode) {
    const list = laneMap.get(node.type);
    if (list) list.push(node);
    for (const child of node.children) {
      walk(child);
    }
  }

  for (const root of roots) walk(root);
  return laneMap;
}

function renderNodeHtml(node: TreeNode): string {
  const html = marked.parse(node.content) as string;
  return `<article class="node" id="node-${node.id}">
  <h3 class="node-title">${escapeHtml(node.title)}</h3>
  <div class="node-content">${html}</div>
</article>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export async function generateProjectHtml(
  projectId: string,
  projectName: string
): Promise<string> {
  const { nodes, edges } = await getProjectGraph(projectId);
  const roots = buildTree(nodes, edges);
  const laneMap = collectByLane(roots);

  // Build TOC and sections
  const tocItems: string[] = [];
  const sections: string[] = [];

  for (const lane of LANE_ORDER) {
    const laneNodes = laneMap.get(lane) || [];
    if (laneNodes.length === 0) continue;
    if (lane === "overview") continue; // skip overview in main content

    const label = NODE_LABELS[lane] || lane;
    tocItems.push(
      `<li><a href="#section-${lane}">${label}（${laneNodes.length}件）</a></li>`
    );

    const articles = laneNodes.map(renderNodeHtml).join("\n");
    sections.push(`<section id="section-${lane}">
  <h2 class="section-title">${label}</h2>
  ${articles}
</section>`);
  }

  const now = new Date().toLocaleString("ja-JP", { timeZone: "Asia/Tokyo" });

  return `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(projectName)}</title>
<style>
${CSS_CONTENT}
</style>
<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
  mermaid.initialize({ startOnLoad: true, theme: 'default' });
</script>
</head>
<body>
<header>
  <h1>${escapeHtml(projectName)}</h1>
  <p class="meta">出力日時: ${now}</p>
</header>
<nav>
  <h2>目次</h2>
  <ul>${tocItems.join("\n    ")}</ul>
</nav>
<main>
${sections.join("\n")}
</main>
<footer>
  <p>Generated by VibeShift</p>
</footer>
</body>
</html>`;
}

const CSS_CONTENT = `
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: "Hiragino Sans", "Noto Sans JP", "Yu Gothic", sans-serif;
  line-height: 1.7;
  color: #1a1a1a;
  max-width: 960px;
  margin: 0 auto;
  padding: 2rem;
  background: #fff;
}
header {
  border-bottom: 3px solid #2563eb;
  padding-bottom: 1rem;
  margin-bottom: 2rem;
}
header h1 { font-size: 1.8rem; color: #1e3a5f; }
header .meta { font-size: 0.85rem; color: #6b7280; margin-top: 0.3rem; }
nav {
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 1rem 1.5rem;
  margin-bottom: 2rem;
}
nav h2 { font-size: 1rem; margin-bottom: 0.5rem; color: #475569; }
nav ul { list-style: none; display: flex; flex-wrap: wrap; gap: 0.5rem 1.5rem; }
nav a { color: #2563eb; text-decoration: none; font-size: 0.9rem; }
nav a:hover { text-decoration: underline; }
.section-title {
  font-size: 1.4rem;
  color: #1e3a5f;
  border-left: 4px solid #2563eb;
  padding-left: 0.75rem;
  margin: 2rem 0 1rem;
}
.node {
  background: #fafbfc;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  padding: 1.2rem 1.5rem;
  margin-bottom: 1rem;
}
.node-title {
  font-size: 1.1rem;
  color: #1e40af;
  margin-bottom: 0.5rem;
  padding-bottom: 0.3rem;
  border-bottom: 1px solid #e5e7eb;
}
.node-content h1, .node-content h2, .node-content h3,
.node-content h4 { margin-top: 1rem; margin-bottom: 0.3rem; color: #334155; }
.node-content h2 { font-size: 1.1rem; }
.node-content h3 { font-size: 1rem; }
.node-content p { margin: 0.4rem 0; }
.node-content ul, .node-content ol { margin: 0.4rem 0 0.4rem 1.5rem; }
.node-content pre {
  background: #f1f5f9;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  padding: 0.8rem;
  overflow-x: auto;
  font-size: 0.8rem;
  margin: 0.5rem 0;
}
.node-content pre.mermaid {
  background: #fff;
  border: 1px solid #e2e8f0;
  text-align: center;
  padding: 1rem;
}
.node-content code {
  background: #f1f5f9;
  padding: 0.1rem 0.3rem;
  border-radius: 3px;
  font-size: 0.85em;
}
.node-content pre code {
  background: none;
  padding: 0;
}
.node-content table {
  border-collapse: collapse;
  width: 100%;
  margin: 0.5rem 0;
  font-size: 0.85rem;
}
.node-content th, .node-content td {
  border: 1px solid #d1d5db;
  padding: 0.4rem 0.6rem;
  text-align: left;
}
.node-content th { background: #f1f5f9; font-weight: 600; }
footer {
  margin-top: 3rem;
  padding-top: 1rem;
  border-top: 1px solid #e5e7eb;
  text-align: center;
  font-size: 0.8rem;
  color: #9ca3af;
}
@media print {
  body { max-width: none; padding: 0; }
  nav { display: none; }
  .node { break-inside: avoid; }
  .section-title { break-before: page; }
  footer { position: fixed; bottom: 0; width: 100%; }
}
`;
